# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3f9b9f7117ba29c8e65b6fff2c24df6227091e375f607afc50f363b0f28b2f8c286921bf86bf2fbb8a63f2337639cbc706c4cc3d8302908432545ccb00d45a

test:
  secret_key_base: d58d2a5383855f22d5025b175d7e5e3f6b4274538b2abadba156044066ca0d61aeefec0ffbb448d0e229b5dc5bcea24c487f49c13e212f3fb5fae442b15027f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
